In [6]:
import pandas as pd

# Working With JSON

In [3]:
pd.read_json('train.json')

          id      cuisine                                        ingredients
0      10259        greek  [romaine lettuce, black olives, grape tomatoes...
1      25693  southern_us  [plain flour, ground pepper, salt, tomatoes, g...
2      20130     filipino  [eggs, pepper, salt, mayonaise, cooking oil, g...
3      22213       indian                [water, vegetable oil, wheat, salt]
4      13162       indian  [black pepper, shallots, cornflour, cayenne pe...
...      ...          ...                                                ...
39769  29109        irish  [light brown sugar, granulated sugar, butter, ...
39770  11462      italian  [KRAFT Zesty Italian Dressing, purple onion, b...
39771   2238        irish  [eggs, citrus fruit, raisins, sourdough starte...
39772  41882      chinese  [boneless chicken skinless thigh, minced garli...
39773   2362      mexican  [green chile, jalapeno chilies, onions, ground...

[39774 rows x 3 columns]

In [4]:
pd.read_json('https://api.exchangerate-api.com/v4/latest/INR')

,provider,WARNING_UPGRADE_TO_V6,terms,base,date,time_last_updated,rates
INR,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-09-29,1790640001,1.0000
AED,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-09-29,1790640001,0.0382
AFN,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-09-29,1790640001,0.6660
ALL,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-09-29,1790640001,0.8420
AMD,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-09-29,1790640001,3.7900
...,...,...,...,...,...,...,...
YER,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-09-29,1790640001,2.4600
ZAR,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-09-29,1790640001,0.1710
ZMW,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-09-29,1790640001,0.2050
ZWG,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-09-29,1790640001,0.2790
ZWL,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-09-29,1790640001,0.2790

# Working with SQL data

In [1]:
import mysql.connector

In [4]:
conn=mysql.connector.connect(host='localhost', user='root',password='',database='world')

In [28]:
pd.read_sql_query("\n SELECT*FROM city GROUP BY CountryCode  HAVING Population <= 100000" , conn)

C:\Users\Shraddha Maurya\AppData\Local\Temp\ipykernel_7304\3573125899.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql_query("\n SELECT*FROM city GROUP BY CountryCode  HAVING Population <= 100000" , conn)

      ID              Name CountryCode          District  Population
0    129        Oranjestad         ABW                 –       29034
1     61        South Hill         AIA                 –         961
2     55  Andorra la Vella         AND  Andorra la Vella       21189
3     33        Willemstad         ANT           Curaçao        2345
4     53            Tafuna         ASM           Tutuila        5200
..   ...               ...         ...               ...         ...
65   537         Road Town         VGB           Tortola        8000
66  4067  Charlotte Amalie         VIR         St Thomas       13000
67  3537         Port-Vila         VUT             Shefa       33700
68  3536          Mata-Utu         WLF            Wallis        1137
69  3169              Apia         WSM             Upolu       35900

[70 rows x 5 columns]

In [30]:
df = pd.read_sql_query("SELECT*FROM countrylanguage", conn)
df

C:\Users\Shraddha Maurya\AppData\Local\Temp\ipykernel_7304\3773656427.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query("SELECT*FROM countrylanguage", conn)

    CountryCode    Language IsOfficial  Percentage
0           ABW       Dutch          T         5.3
1           ABW     English          F         9.5
2           ABW  Papiamento          F        76.7
3           ABW     Spanish          F         7.4
4           AFG     Balochi          F         0.9
..          ...         ...        ...         ...
979         ZMB      Tongan          F        11.0
980         ZWE     English          T         2.2
981         ZWE     Ndebele          F        16.2
982         ZWE      Nyanja          F         2.2
983         ZWE       Shona          F        72.1

[984 rows x 4 columns]